# Generated by Django 4.1.3 on 2023-11-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('pname', models.TextField()),
                ('gender', models.TextField()),
                ('pbrand', models.TextField()),
                ('price', models.IntegerField()),
                ('desc', models.TextField()),
                ('color', models.TextField()),
            ],
        ),
    ]
