# Generated by Django 4.1.3 on 2023-11-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='gender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='pbrand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='pid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='pname',
            field=models.CharField(max_length=100),
        ),
    ]
